<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="leo.20151212173315.1"><vh>@settings</vh>
<v t="leo.20151212173315.2"><vh>@data qt-gui-plugin-style-sheet</vh></v>
<v t="leo.20151212173315.3"><vh>@string initial_split_orientation = horizontal</vh></v>
</v>
<v t="amd.20160921213353.1"><vh>2016fall 簡報與網誌樣板系統</vh></v>
<v t="amd.20160106095324.1" a="E"><vh>@path ./../</vh>
<v t="leo.20151213173830.1" a="E"><vh>假如要在近端檢視, 使用下列按鈕</vh>
<v t="leo.20161118111218.1"><vh>@button https server</vh></v>
<v t="leo.20151213085727.1"><vh>@button pelican-blog</vh></v>
</v>
<v t="amd.20151215180106.1" a="E"><vh>設定與開發</vh>
<v t="leo.20161013190948.1"><vh>@@edit index.html</vh></v>
<v t="leo.20161014111031.1"><vh>@clean index.html</vh>
<v t="leo.20161014111031.2" a="E"><vh>html</vh>
<v t="leo.20161014111031.3"><vh>head</vh></v>
<v t="leo.20161014111031.4" a="E"><vh>body</vh>
<v t="leo.20161014111031.5" a="E"><vh>reveal div</vh>
<v t="leo.20161014111031.6" a="E"><vh>slides div</vh>
<v t="leo.20161014111031.7" a="E"><vh>封面投影片</vh>
<v t="leo.20161014111031.8"><vh>封面投影片內容</vh></v>
</v>
<v t="leo.20161014111031.9"><vh>20160916W1</vh>
<v t="leo.20161104010025.1"><vh>上課日期</vh>
<v t="leo.20161104010025.2"><vh>20160916</vh></v>
</v>
<v t="leo.20161014111031.10"><vh>上課內容1</vh>
<v t="leo.20161014111031.11"><vh>中秋連假</vh></v>
</v>
</v>
<v t="leo.20161014111031.24"><vh>20160923W2</vh>
<v t="leo.20161104010248.1"><vh>上課日期</vh>
<v t="leo.20161104010248.2"><vh>20160923</vh></v>
</v>
<v t="leo.20161014111031.25"><vh>上課內容1</vh>
<v t="leo.20161014111031.26"><vh>建立40423226.github.io名稱的倉儲</vh></v>
</v>
<v t="leo.20161014111031.27"><vh>上課內容2</vh>
<v t="leo.20161014111031.28"><vh>把分支的預設值改為gh-pages</vh></v>
</v>
</v>
<v t="leo.20161014111031.37"><vh>20160930W3</vh>
<v t="leo.20161104010457.1"><vh>上課日期</vh>
<v t="leo.20161104010457.2"><vh>20160930</vh></v>
</v>
<v t="leo.20161014111031.38"><vh>上課內容1</vh>
<v t="leo.20161014111031.39"><vh>複製網誌和簡報的設定檔到2016fallcadp_hw的倉儲</vh></v>
</v>
<v t="leo.20161104010537.1"><vh>上課內容2</vh>
<v t="leo.20161104010537.2"><vh>更改2016fallcadp_hw的README.md檔案</vh></v>
</v>
</v>
<v t="leo.20161014111031.40"><vh>20161007W4</vh>
<v t="leo.20161104010854.1"><vh>上課日期</vh>
<v t="leo.20161104010854.2"><vh>20161007</vh></v>
</v>
<v t="leo.20161014111031.41"><vh>上課內容1</vh>
<v t="leo.20161014111031.42"><vh>設定使用者資料,讓可攜程式更方便</vh></v>
</v>
<v t="leo.20161014111031.43"><vh>上課內容2</vh>
<v t="leo.20161014111031.44"><vh>用2016fallcadp_bg6的名稱,建立小組倉儲</vh></v>
</v>
</v>
<v t="leo.20161103232830.1"><vh>20161014W5</vh>
<v t="leo.20161104011343.1"><vh>上課日期</vh>
<v t="leo.20161104011343.2"><vh>20161014</vh></v>
</v>
<v t="leo.20161103232830.2"><vh>上課內容1</vh>
<v t="leo.20161103232830.3"><vh>初步認識SolveSpace</vh></v>
</v>
</v>
<v t="leo.20161103232832.1"><vh>20161021W6</vh>
<v t="leo.20161104011407.1"><vh>上課日期</vh>
<v t="leo.20161104011407.2"><vh>20161021</vh></v>
</v>
<v t="leo.20161103232832.2"><vh>上課內容1</vh>
<v t="leo.20161103232832.3"><vh>解決子模組在對應上的問題</vh></v>
</v>
</v>
<v t="leo.20161103233616.1"><vh>20161028W7</vh>
<v t="leo.20161104011701.1"><vh>上課日期</vh>
<v t="leo.20161104011701.2"><vh>20161028</vh></v>
</v>
<v t="leo.20161103233616.2"><vh>上課內容1</vh>
<v t="leo.20161103233616.3"><vh>使用Trace Point計算路徑</vh></v>
</v>
</v>
<v t="leo.20161104203720.1"><vh>20161104W8</vh>
<v t="leo.20161104203720.2"><vh>上課日期</vh>
<v t="leo.20161104203720.3"><vh>20161104</vh></v>
</v>
<v t="leo.20161104203720.4"><vh>上課內容1</vh>
<v t="leo.20161104203720.5"><vh>期中課程評量</vh></v>
</v>
</v>
<v t="leo.20161115000909.1"><vh>20161111W9</vh>
<v t="leo.20161115000909.2"><vh>上課日期</vh>
<v t="leo.20161115000909.3"><vh>20161118</vh></v>
</v>
<v t="leo.20161115000909.4"><vh>上課內容1</vh>
<v t="leo.20161115000909.5"><vh>期中自我評分</vh></v>
</v>
</v>
<v t="leo.20161124210839.1"><vh>20161118W10</vh>
<v t="leo.20161124210839.2"><vh>上課日期</vh>
<v t="leo.20161124210839.3"><vh>20161118</vh></v>
</v>
<v t="leo.20161124210839.4"><vh>上課內容1</vh>
<v t="leo.20161124210839.5"><vh>Solvespace 平面四連桿機構模擬</vh></v>
</v>
</v>
<v t="leo.20161124210841.1"><vh>20161125W11</vh>
<v t="leo.20161124210841.2"><vh>上課日期</vh>
<v t="leo.20161124210841.3"><vh>20161125</vh></v>
</v>
<v t="leo.20161124210841.4"><vh>上課內容1</vh>
<v t="leo.20161124210841.5"><vh>校慶</vh></v>
</v>
</v>
<v t="leo.20161209165346.1"><vh>20161202W12</vh>
<v t="leo.20161209165346.2"><vh>上課日期</vh>
<v t="leo.20161209165346.3"><vh>20161202</vh></v>
</v>
<v t="leo.20161209174033.1"><vh>上課內容1</vh>
<v t="leo.20161209174033.2"><vh>利用SolveSpace存html檔</vh></v>
</v>
<v t="leo.20161209165346.4"><vh>上課內容2</vh>
<v t="leo.20161209165346.5"><vh>SolveSpace_Cube</vh></v>
</v>
<v t="leo.20161209165937.1"><vh>上課內容3</vh>
<v t="leo.20161209165937.2"><vh>SolveSpace_Strut</vh></v>
</v>
<v t="leo.20161209165942.1"><vh>上課內容4</vh>
<v t="leo.20161209165942.2"><vh>SolveSpace_Combination</vh></v>
</v>
</v>
<v t="leo.20161209165348.1"><vh>20161209W13</vh>
<v t="leo.20161209165348.2"><vh>上課日期</vh>
<v t="leo.20161209165348.3"><vh>20161209</vh></v>
</v>
<v t="leo.20161209165348.4"><vh>上課內容1</vh>
<v t="leo.20161209165348.5"><vh>遠端網誌無法更新</vh></v>
</v>
</v>
<v t="leo.20170101215257.1"><vh>20161216W14</vh>
<v t="leo.20170101215257.2"><vh>上課日期</vh>
<v t="leo.20170101215257.3"><vh>20161216</vh></v>
</v>
<v t="leo.20170101215257.4"><vh>上課內容1</vh>
<v t="leo.20170101215257.5"><vh>delta_printer_v2</vh></v>
</v>
</v>
<v t="leo.20170101215259.1"><vh>20161223W15</vh>
<v t="leo.20170101215259.2"><vh>上課日期</vh>
<v t="leo.20170101215259.3"><vh>20161223</vh></v>
</v>
<v t="leo.20170101215259.4"><vh>上課內容1</vh>
<v t="leo.20170101215259.5"><vh>整理目前為止上課的內容</vh></v>
</v>
</v>
<v t="leo.20170101215301.1"><vh>20161230W16</vh>
<v t="leo.20170101215301.2"><vh>上課日期</vh>
<v t="leo.20170101215301.3"><vh>20161230</vh></v>
</v>
<v t="leo.20170101215301.4"><vh>上課內容1</vh>
<v t="leo.20170101215301.5"><vh>繪製 Mechanism Tutorial</vh></v>
</v>
</v>
<v t="leo.20170112140710.1"><vh>20170106W17</vh>
<v t="leo.20170112140710.2"><vh>上課日期</vh>
<v t="leo.20170112140710.3"><vh>20170106</vh></v>
</v>
<v t="leo.20170112140710.4"><vh>上課內容1</vh>
<v t="leo.20170112140710.5"><vh>相對運動練習</vh></v>
</v>
</v>
<v t="leo.20170113103445.1"><vh>20170113W18</vh>
<v t="leo.20170113103445.2"><vh>上課日期</vh>
<v t="leo.20170113103445.3"><vh>20170113</vh></v>
</v>
<v t="leo.20170113103445.4"><vh>上課內容1</vh>
<v t="leo.20170113103445.5"><vh>期末自評總結</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20151213230723.1"><vh>Pelican 設定</vh>
<v t="leo.20151213230957.1"><vh>文章 Date 設定</vh></v>
<v t="leo.20151213230729.1"><vh>使用 summary plugin</vh></v>
</v>
<v t="amd.20151215170117.1"><vh>以下 pelicanconf.py 為近端與遠端的共同設定</vh></v>
<v t="leo.20151212173725.1"><vh>@edit pelicanconf.py</vh></v>
<v t="amd.20151215170221.1"><vh>以下 local_publishconf.py 為近端所使用的設定</vh></v>
<v t="leo.20151213085752.1"><vh>@edit local_publishconf.py</vh></v>
</v>
</v>
<v t="amd.20151215170350.1"><vh>以下為 content 目錄中的 md 檔案</vh></v>
<v t="amd.20151216001126.1"><vh>md 檔案範例</vh></v>
<v t="amd.20151215170031.1" a="E"><vh>@path ./../content</vh>
<v t="amd.20160106093454.1" a="E"><vh>yen 所寫的網誌文章</vh>
<v t="amd.20160727114506.1" a="E"><vh>201609</vh>
<v t="leo.20161028152823.1"><vh>@edit 20160916.md</vh></v>
<v t="leo.20161028153027.1"><vh>@edit 20160923.md</vh></v>
<v t="leo.20161028153031.1"><vh>@edit 20160930.md</vh></v>
<v t="leo.20161028153033.1"><vh>@edit 20161007.md</vh></v>
<v t="leo.20161028153029.1"><vh>@edit 20161014.md</vh></v>
<v t="leo.20161028153102.1"><vh>@edit 20161021.md</vh></v>
<v t="leo.20161028153104.1"><vh>@edit 20161028.md</vh></v>
<v t="leo.20161104203621.1"><vh>@edit 20161104.md</vh></v>
<v t="leo.20161115000357.1"><vh>@edit 20161111.md</vh></v>
<v t="leo.20161118112100.1"><vh>@edit 20161118.md</vh></v>
<v t="leo.20161124205906.1"><vh>@edit 20161125.md</vh></v>
<v t="leo.20161209153338.1"><vh>@edit 20161202.md</vh></v>
<v t="leo.20161209153340.1"><vh>@edit 20161209.md</vh></v>
<v t="leo.20161230112544.1"><vh>@edit 20161223.md</vh></v>
<v t="leo.20161230112546.1"><vh>@edit 20161230.md</vh></v>
<v t="leo.20170112135759.1"><vh>@edit 20170106.md</vh></v>
<v t="leo.20170113093236.1"><vh>@edit 20170113.md</vh></v>
</v>
</v>
</v>
<v t="amd.20160106094754.1"><vh>@path ./../content/pages</vh>
<v t="amd.20160106094829.1"><vh>yen 所寫的 pages 文章</vh>
<v t="amd.20160106094844.1"><vh>@edit pages_1.md</vh></v>
</v>
</v>
<v t="amd.20161004202833.1"><vh>@edit ../README.md</vh></v>
<v t="leo.20170114173925.2" a="E"><vh>Recovered Nodes</vh>
<v t="leo.20170114173925.3"><vh>Recovered node "head" from @clean index.html</vh>
<v t="leo.20170114173925.4"><vh>old:head</vh></v>
<v t="leo.20170114173925.5"><vh>new:head</vh></v>
</v>
<v t="leo.20170114173925.6"><vh>Recovered node "body" from @clean index.html</vh>
<v t="leo.20170114173925.7"><vh>old:body</vh></v>
<v t="leo.20170114173925.8"><vh>new:body</vh></v>
</v>
<v t="leo.20170114173925.9"><vh>Recovered node "reveal div" from @clean index.html</vh>
<v t="leo.20170114173925.10"><vh>old:reveal div</vh></v>
<v t="leo.20170114173925.11"><vh>new:reveal div</vh></v>
</v>
<v t="leo.20170114173925.12"><vh>Recovered node "slides div" from @clean index.html</vh>
<v t="leo.20170114173925.13"><vh>old:slides div</vh></v>
<v t="leo.20170114173925.14"><vh>new:slides div</vh></v>
</v>
<v t="leo.20170114173925.15"><vh>Recovered node "封面投影片" from @clean index.html</vh>
<v t="leo.20170114173925.16"><vh>old:封面投影片</vh></v>
<v t="leo.20170114173925.17"><vh>new:封面投影片</vh></v>
</v>
<v t="leo.20170114173925.18"><vh>Recovered node "封面投影片內容" from @clean index.html</vh>
<v t="leo.20170114173925.19"><vh>old:封面投影片內容</vh></v>
<v t="leo.20170114173925.20"><vh>new:封面投影片內容</vh></v>
</v>
<v t="leo.20170114173925.21"><vh>Recovered node "20160916W1" from @clean index.html</vh>
<v t="leo.20170114173925.22"><vh>old:20160916W1</vh></v>
<v t="leo.20170114173925.23"><vh>new:20160916W1</vh></v>
</v>
<v t="leo.20170114173925.24"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170114173925.25"><vh>old:上課日期</vh></v>
<v t="leo.20170114173925.26"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170114173925.27"><vh>Recovered node "20160916" from @clean index.html</vh>
<v t="leo.20170114173925.28"><vh>old:20160916</vh></v>
<v t="leo.20170114173925.29"><vh>new:20160916</vh></v>
</v>
<v t="leo.20170114173925.30"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170114173925.31"><vh>old:上課內容1</vh></v>
<v t="leo.20170114173925.32"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170114173925.33"><vh>Recovered node "中秋連假" from @clean index.html</vh>
<v t="leo.20170114173925.34"><vh>old:中秋連假</vh></v>
<v t="leo.20170114173925.35"><vh>new:中秋連假</vh></v>
</v>
<v t="leo.20170114173925.36"><vh>Recovered node "20160923W2" from @clean index.html</vh>
<v t="leo.20170114173925.37"><vh>old:20160923W2</vh></v>
<v t="leo.20170114173925.38"><vh>new:20160923W2</vh></v>
</v>
<v t="leo.20170114173925.39"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170114173925.40"><vh>old:上課日期</vh></v>
<v t="leo.20170114173925.41"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170114173925.42"><vh>Recovered node "20160923" from @clean index.html</vh>
<v t="leo.20170114173925.43"><vh>old:20160923</vh></v>
<v t="leo.20170114173925.44"><vh>new:20160923</vh></v>
</v>
<v t="leo.20170114173925.45"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170114173925.46"><vh>old:上課內容1</vh></v>
<v t="leo.20170114173925.47"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170114173925.48"><vh>Recovered node "建立40423226.github.io名稱的倉儲" from @clean index.html</vh>
<v t="leo.20170114173925.49"><vh>old:建立40423226.github.io名稱的倉儲</vh></v>
<v t="leo.20170114173925.50"><vh>new:建立40423226.github.io名稱的倉儲</vh></v>
</v>
<v t="leo.20170114173925.51"><vh>Recovered node "上課內容2" from @clean index.html</vh>
<v t="leo.20170114173925.52"><vh>old:上課內容2</vh></v>
<v t="leo.20170114173925.53"><vh>new:上課內容2</vh></v>
</v>
<v t="leo.20170114173925.54"><vh>Recovered node "把分支的預設值改為gh-pages" from @clean index.html</vh>
<v t="leo.20170114173925.55"><vh>old:把分支的預設值改為gh-pages</vh></v>
<v t="leo.20170114173925.56"><vh>new:把分支的預設值改為gh-pages</vh></v>
</v>
<v t="leo.20170114173925.57"><vh>Recovered node "20160930W3" from @clean index.html</vh>
<v t="leo.20170114173925.58"><vh>old:20160930W3</vh></v>
<v t="leo.20170114173925.59"><vh>new:20160930W3</vh></v>
</v>
<v t="leo.20170114173925.60"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170114173925.61"><vh>old:上課日期</vh></v>
<v t="leo.20170114173925.62"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170114173925.63"><vh>Recovered node "20160930" from @clean index.html</vh>
<v t="leo.20170114173925.64"><vh>old:20160930</vh></v>
<v t="leo.20170114173925.65"><vh>new:20160930</vh></v>
</v>
<v t="leo.20170114173925.66"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170114173925.67"><vh>old:上課內容1</vh></v>
<v t="leo.20170114173925.68"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170114173925.69"><vh>Recovered node "複製網誌和簡報的設定檔到2016fallcadp_hw的倉儲" from @clean index.html</vh>
<v t="leo.20170114173925.70"><vh>old:複製網誌和簡報的設定檔到2016fallcadp_hw的倉儲</vh></v>
<v t="leo.20170114173925.71"><vh>new:複製網誌和簡報的設定檔到2016fallcadp_hw的倉儲</vh></v>
</v>
<v t="leo.20170114173925.72"><vh>Recovered node "上課內容2" from @clean index.html</vh>
<v t="leo.20170114173925.73"><vh>old:上課內容2</vh></v>
<v t="leo.20170114173925.74"><vh>new:上課內容2</vh></v>
</v>
<v t="leo.20170114173925.75"><vh>Recovered node "更改2016fallcadp_hw的README.md檔案" from @clean index.html</vh>
<v t="leo.20170114173925.76"><vh>old:更改2016fallcadp_hw的README.md檔案</vh></v>
<v t="leo.20170114173925.77"><vh>new:更改2016fallcadp_hw的README.md檔案</vh></v>
</v>
<v t="leo.20170114173925.78"><vh>Recovered node "20161007W4" from @clean index.html</vh>
<v t="leo.20170114173925.79"><vh>old:20161007W4</vh></v>
<v t="leo.20170114173925.80"><vh>new:20161007W4</vh></v>
</v>
<v t="leo.20170114173925.81"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170114173925.82"><vh>old:上課日期</vh></v>
<v t="leo.20170114173925.83"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170114173925.84"><vh>Recovered node "20161007" from @clean index.html</vh>
<v t="leo.20170114173925.85"><vh>old:20161007</vh></v>
<v t="leo.20170114173925.86"><vh>new:20161007</vh></v>
</v>
<v t="leo.20170114173925.87"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170114173925.88"><vh>old:上課內容1</vh></v>
<v t="leo.20170114173925.89"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170114173925.90"><vh>Recovered node "設定使用者資料,讓可攜程式更方便" from @clean index.html</vh>
<v t="leo.20170114173925.91"><vh>old:設定使用者資料,讓可攜程式更方便</vh></v>
<v t="leo.20170114173925.92"><vh>new:設定使用者資料,讓可攜程式更方便</vh></v>
</v>
<v t="leo.20170114173925.93"><vh>Recovered node "上課內容2" from @clean index.html</vh>
<v t="leo.20170114173925.94"><vh>old:上課內容2</vh></v>
<v t="leo.20170114173925.95"><vh>new:上課內容2</vh></v>
</v>
<v t="leo.20170114173925.96"><vh>Recovered node "用2016fallcadp_bg6的名稱,建立小組倉儲" from @clean index.html</vh>
<v t="leo.20170114173925.97"><vh>old:用2016fallcadp_bg6的名稱,建立小組倉儲</vh></v>
<v t="leo.20170114173925.98"><vh>new:用2016fallcadp_bg6的名稱,建立小組倉儲</vh></v>
</v>
<v t="leo.20170114173925.99"><vh>Recovered node "20161014W5" from @clean index.html</vh>
<v t="leo.20170114173925.100"><vh>old:20161014W5</vh></v>
<v t="leo.20170114173925.101"><vh>new:20161014W5</vh></v>
</v>
<v t="leo.20170114173925.102"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170114173925.103"><vh>old:上課日期</vh></v>
<v t="leo.20170114173925.104"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170114173925.105"><vh>Recovered node "20161014" from @clean index.html</vh>
<v t="leo.20170114173925.106"><vh>old:20161014</vh></v>
<v t="leo.20170114173925.107"><vh>new:20161014</vh></v>
</v>
<v t="leo.20170114173925.108"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170114173925.109"><vh>old:上課內容1</vh></v>
<v t="leo.20170114173925.110"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170114173925.111"><vh>Recovered node "初步認識SolveSpace" from @clean index.html</vh>
<v t="leo.20170114173925.112"><vh>old:初步認識SolveSpace</vh></v>
<v t="leo.20170114173925.113"><vh>new:初步認識SolveSpace</vh></v>
</v>
<v t="leo.20170114173925.114"><vh>Recovered node "20161021W6" from @clean index.html</vh>
<v t="leo.20170114173925.115"><vh>old:20161021W6</vh></v>
<v t="leo.20170114173925.116"><vh>new:20161021W6</vh></v>
</v>
<v t="leo.20170114173925.117"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170114173925.118"><vh>old:上課日期</vh></v>
<v t="leo.20170114173925.119"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170114173925.120"><vh>Recovered node "20161021" from @clean index.html</vh>
<v t="leo.20170114173925.121"><vh>old:20161021</vh></v>
<v t="leo.20170114173925.122"><vh>new:20161021</vh></v>
</v>
<v t="leo.20170114173925.123"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170114173925.124"><vh>old:上課內容1</vh></v>
<v t="leo.20170114173925.125"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170114173925.126"><vh>Recovered node "解決子模組在對應上的問題" from @clean index.html</vh>
<v t="leo.20170114173925.127"><vh>old:解決子模組在對應上的問題</vh></v>
<v t="leo.20170114173925.128"><vh>new:解決子模組在對應上的問題</vh></v>
</v>
<v t="leo.20170114173925.129"><vh>Recovered node "20161028W7" from @clean index.html</vh>
<v t="leo.20170114173925.130"><vh>old:20161028W7</vh></v>
<v t="leo.20170114173925.131"><vh>new:20161028W7</vh></v>
</v>
<v t="leo.20170114173925.132"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170114173925.133"><vh>old:上課日期</vh></v>
<v t="leo.20170114173925.134"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170114173925.135"><vh>Recovered node "20161028" from @clean index.html</vh>
<v t="leo.20170114173925.136"><vh>old:20161028</vh></v>
<v t="leo.20170114173925.137"><vh>new:20161028</vh></v>
</v>
<v t="leo.20170114173925.138"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170114173925.139"><vh>old:上課內容1</vh></v>
<v t="leo.20170114173925.140"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170114173925.141"><vh>Recovered node "使用Trace Point計算路徑" from @clean index.html</vh>
<v t="leo.20170114173925.142"><vh>old:使用Trace Point計算路徑</vh></v>
<v t="leo.20170114173925.143"><vh>new:使用Trace Point計算路徑</vh></v>
</v>
<v t="leo.20170114173925.144"><vh>Recovered node "20161104W8" from @clean index.html</vh>
<v t="leo.20170114173925.145"><vh>old:20161104W8</vh></v>
<v t="leo.20170114173925.146"><vh>new:20161104W8</vh></v>
</v>
<v t="leo.20170114173925.147"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170114173925.148"><vh>old:上課日期</vh></v>
<v t="leo.20170114173925.149"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170114173925.150"><vh>Recovered node "20161104" from @clean index.html</vh>
<v t="leo.20170114173925.151"><vh>old:20161104</vh></v>
<v t="leo.20170114173925.152"><vh>new:20161104</vh></v>
</v>
<v t="leo.20170114173925.153"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170114173925.154"><vh>old:上課內容1</vh></v>
<v t="leo.20170114173925.155"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170114173925.156"><vh>Recovered node "期中課程評量" from @clean index.html</vh>
<v t="leo.20170114173925.157"><vh>old:期中課程評量</vh></v>
<v t="leo.20170114173925.158"><vh>new:期中課程評量</vh></v>
</v>
<v t="leo.20170114173925.159"><vh>Recovered node "20161111W9" from @clean index.html</vh>
<v t="leo.20170114173925.160"><vh>old:20161111W9</vh></v>
<v t="leo.20170114173925.161"><vh>new:20161111W9</vh></v>
</v>
<v t="leo.20170114173925.162"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170114173925.163"><vh>old:上課日期</vh></v>
<v t="leo.20170114173925.164"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170114173925.165"><vh>Recovered node "20161118" from @clean index.html</vh>
<v t="leo.20170114173925.166"><vh>old:20161118</vh></v>
<v t="leo.20170114173925.167"><vh>new:20161118</vh></v>
</v>
<v t="leo.20170114173925.168"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170114173925.169"><vh>old:上課內容1</vh></v>
<v t="leo.20170114173925.170"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170114173925.171"><vh>Recovered node "期中自我評分" from @clean index.html</vh>
<v t="leo.20170114173925.172"><vh>old:期中自我評分</vh></v>
<v t="leo.20170114173925.173"><vh>new:期中自我評分</vh></v>
</v>
<v t="leo.20170114173925.174"><vh>Recovered node "20161118W10" from @clean index.html</vh>
<v t="leo.20170114173925.175"><vh>old:20161118W10</vh></v>
<v t="leo.20170114173925.176"><vh>new:20161118W10</vh></v>
</v>
<v t="leo.20170114173925.177"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170114173925.178"><vh>old:上課日期</vh></v>
<v t="leo.20170114173925.179"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170114173925.180"><vh>Recovered node "20161118" from @clean index.html</vh>
<v t="leo.20170114173925.181"><vh>old:20161118</vh></v>
<v t="leo.20170114173925.182"><vh>new:20161118</vh></v>
</v>
<v t="leo.20170114173925.183"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170114173925.184"><vh>old:上課內容1</vh></v>
<v t="leo.20170114173925.185"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170114173925.186"><vh>Recovered node "Solvespace 平面四連桿機構模擬" from @clean index.html</vh>
<v t="leo.20170114173925.187"><vh>old:Solvespace 平面四連桿機構模擬</vh></v>
<v t="leo.20170114173925.188"><vh>new:Solvespace 平面四連桿機構模擬</vh></v>
</v>
<v t="leo.20170114173925.189"><vh>Recovered node "20161125W11" from @clean index.html</vh>
<v t="leo.20170114173925.190"><vh>old:20161125W11</vh></v>
<v t="leo.20170114173925.191"><vh>new:20161125W11</vh></v>
</v>
<v t="leo.20170114173925.192"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170114173925.193"><vh>old:上課日期</vh></v>
<v t="leo.20170114173925.194"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170114173925.195"><vh>Recovered node "20161125" from @clean index.html</vh>
<v t="leo.20170114173925.196"><vh>old:20161125</vh></v>
<v t="leo.20170114173925.197"><vh>new:20161125</vh></v>
</v>
<v t="leo.20170114173925.198"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170114173925.199"><vh>old:上課內容1</vh></v>
<v t="leo.20170114173925.200"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170114173925.201"><vh>Recovered node "校慶" from @clean index.html</vh>
<v t="leo.20170114173925.202"><vh>old:校慶</vh></v>
<v t="leo.20170114173925.203"><vh>new:校慶</vh></v>
</v>
<v t="leo.20170114173925.204"><vh>Recovered node "20161202W12" from @clean index.html</vh>
<v t="leo.20170114173925.205"><vh>old:20161202W12</vh></v>
<v t="leo.20170114173925.206"><vh>new:20161202W12</vh></v>
</v>
<v t="leo.20170114173925.207"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170114173925.208"><vh>old:上課日期</vh></v>
<v t="leo.20170114173925.209"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170114173925.210"><vh>Recovered node "20161202" from @clean index.html</vh>
<v t="leo.20170114173925.211"><vh>old:20161202</vh></v>
<v t="leo.20170114173925.212"><vh>new:20161202</vh></v>
</v>
<v t="leo.20170114173925.213"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170114173925.214"><vh>old:上課內容1</vh></v>
<v t="leo.20170114173925.215"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170114173925.216"><vh>Recovered node "利用SolveSpace存html檔" from @clean index.html</vh>
<v t="leo.20170114173925.217"><vh>old:利用SolveSpace存html檔</vh></v>
<v t="leo.20170114173925.218"><vh>new:利用SolveSpace存html檔</vh></v>
</v>
<v t="leo.20170114173925.219"><vh>Recovered node "上課內容2" from @clean index.html</vh>
<v t="leo.20170114173925.220"><vh>old:上課內容2</vh></v>
<v t="leo.20170114173925.221"><vh>new:上課內容2</vh></v>
</v>
<v t="leo.20170114173925.222"><vh>Recovered node "SolveSpace_Cube" from @clean index.html</vh>
<v t="leo.20170114173925.223"><vh>old:SolveSpace_Cube</vh></v>
<v t="leo.20170114173925.224"><vh>new:SolveSpace_Cube</vh></v>
</v>
<v t="leo.20170114173925.225"><vh>Recovered node "上課內容3" from @clean index.html</vh>
<v t="leo.20170114173925.226"><vh>old:上課內容3</vh></v>
<v t="leo.20170114173925.227"><vh>new:上課內容3</vh></v>
</v>
<v t="leo.20170114173925.228"><vh>Recovered node "SolveSpace_Strut" from @clean index.html</vh>
<v t="leo.20170114173925.229"><vh>old:SolveSpace_Strut</vh></v>
<v t="leo.20170114173925.230"><vh>new:SolveSpace_Strut</vh></v>
</v>
<v t="leo.20170114173925.231"><vh>Recovered node "上課內容4" from @clean index.html</vh>
<v t="leo.20170114173925.232"><vh>old:上課內容4</vh></v>
<v t="leo.20170114173925.233"><vh>new:上課內容4</vh></v>
</v>
<v t="leo.20170114173925.234"><vh>Recovered node "SolveSpace_Combination" from @clean index.html</vh>
<v t="leo.20170114173925.235"><vh>old:SolveSpace_Combination</vh></v>
<v t="leo.20170114173925.236"><vh>new:SolveSpace_Combination</vh></v>
</v>
<v t="leo.20170114173925.237"><vh>Recovered node "20161209W13" from @clean index.html</vh>
<v t="leo.20170114173925.238"><vh>old:20161209W13</vh></v>
<v t="leo.20170114173925.239"><vh>new:20161209W13</vh></v>
</v>
<v t="leo.20170114173925.240"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170114173925.241"><vh>old:上課日期</vh></v>
<v t="leo.20170114173925.242"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170114173925.243"><vh>Recovered node "20161209" from @clean index.html</vh>
<v t="leo.20170114173925.244"><vh>old:20161209</vh></v>
<v t="leo.20170114173925.245"><vh>new:20161209</vh></v>
</v>
<v t="leo.20170114173925.246"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170114173925.247"><vh>old:上課內容1</vh></v>
<v t="leo.20170114173925.248"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170114173925.249"><vh>Recovered node "遠端網誌無法更新" from @clean index.html</vh>
<v t="leo.20170114173925.250"><vh>old:遠端網誌無法更新</vh></v>
<v t="leo.20170114173925.251"><vh>new:遠端網誌無法更新</vh></v>
</v>
<v t="leo.20170114173925.252"><vh>Recovered node "20161216W14" from @clean index.html</vh>
<v t="leo.20170114173925.253"><vh>old:20161216W14</vh></v>
<v t="leo.20170114173925.254"><vh>new:20161216W14</vh></v>
</v>
<v t="leo.20170114173925.255"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170114173925.256"><vh>old:上課日期</vh></v>
<v t="leo.20170114173925.257"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170114173925.258"><vh>Recovered node "20161216" from @clean index.html</vh>
<v t="leo.20170114173925.259"><vh>old:20161216</vh></v>
<v t="leo.20170114173925.260"><vh>new:20161216</vh></v>
</v>
<v t="leo.20170114173925.261"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170114173925.262"><vh>old:上課內容1</vh></v>
<v t="leo.20170114173925.263"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170114173925.264"><vh>Recovered node "delta_printer_v2" from @clean index.html</vh>
<v t="leo.20170114173925.265"><vh>old:delta_printer_v2</vh></v>
<v t="leo.20170114173925.266"><vh>new:delta_printer_v2</vh></v>
</v>
<v t="leo.20170114173925.267"><vh>Recovered node "20161223W15" from @clean index.html</vh>
<v t="leo.20170114173925.268"><vh>old:20161223W15</vh></v>
<v t="leo.20170114173925.269"><vh>new:20161223W15</vh></v>
</v>
<v t="leo.20170114173925.270"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170114173925.271"><vh>old:上課日期</vh></v>
<v t="leo.20170114173925.272"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170114173925.273"><vh>Recovered node "20161223" from @clean index.html</vh>
<v t="leo.20170114173925.274"><vh>old:20161223</vh></v>
<v t="leo.20170114173925.275"><vh>new:20161223</vh></v>
</v>
<v t="leo.20170114173925.276"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170114173925.277"><vh>old:上課內容1</vh></v>
<v t="leo.20170114173925.278"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170114173925.279"><vh>Recovered node "整理目前為止上課的內容" from @clean index.html</vh>
<v t="leo.20170114173925.280"><vh>old:整理目前為止上課的內容</vh></v>
<v t="leo.20170114173925.281"><vh>new:整理目前為止上課的內容</vh></v>
</v>
<v t="leo.20170114173925.282"><vh>Recovered node "20161230W16" from @clean index.html</vh>
<v t="leo.20170114173925.283"><vh>old:20161230W16</vh></v>
<v t="leo.20170114173925.284"><vh>new:20161230W16</vh></v>
</v>
<v t="leo.20170114173925.285"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170114173925.286"><vh>old:上課日期</vh></v>
<v t="leo.20170114173925.287"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170114173925.288"><vh>Recovered node "20161230" from @clean index.html</vh>
<v t="leo.20170114173925.289"><vh>old:20161230</vh></v>
<v t="leo.20170114173925.290"><vh>new:20161230</vh></v>
</v>
<v t="leo.20170114173925.291"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170114173925.292"><vh>old:上課內容1</vh></v>
<v t="leo.20170114173925.293"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170114173925.294"><vh>Recovered node "繪製 Mechanism Tutorial" from @clean index.html</vh>
<v t="leo.20170114173925.295"><vh>old:繪製 Mechanism Tutorial</vh></v>
<v t="leo.20170114173925.296"><vh>new:繪製 Mechanism Tutorial</vh></v>
</v>
<v t="leo.20170114173925.297"><vh>Recovered node "20170106W17" from @clean index.html</vh>
<v t="leo.20170114173925.298"><vh>old:20170106W17</vh></v>
<v t="leo.20170114173925.299"><vh>new:20170106W17</vh></v>
</v>
<v t="leo.20170114173925.300"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170114173925.301"><vh>old:上課日期</vh></v>
<v t="leo.20170114173925.302"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170114173925.303"><vh>Recovered node "20170106" from @clean index.html</vh>
<v t="leo.20170114173925.304"><vh>old:20170106</vh></v>
<v t="leo.20170114173925.305"><vh>new:20170106</vh></v>
</v>
<v t="leo.20170114173925.306"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170114173925.307"><vh>old:上課內容1</vh></v>
<v t="leo.20170114173925.308"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170114173925.309"><vh>Recovered node "相對運動練習" from @clean index.html</vh>
<v t="leo.20170114173925.310"><vh>old:相對運動練習</vh></v>
<v t="leo.20170114173925.311"><vh>new:相對運動練習</vh></v>
</v>
<v t="leo.20170114173925.312"><vh>Recovered node "20170113W18" from @clean index.html</vh>
<v t="leo.20170114173925.313"><vh>old:20170113W18</vh></v>
<v t="leo.20170114173925.314"><vh>new:20170113W18</vh></v>
</v>
<v t="leo.20170114173925.315"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170114173925.316"><vh>old:上課日期</vh></v>
<v t="leo.20170114173925.317"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170114173925.318"><vh>Recovered node "20170113" from @clean index.html</vh>
<v t="leo.20170114173925.319"><vh>old:20170113</vh></v>
<v t="leo.20170114173925.320"><vh>new:20170113</vh></v>
</v>
<v t="leo.20170114173925.321"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170114173925.322"><vh>old:上課內容1</vh></v>
<v t="leo.20170114173925.323"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170114173925.324"><vh>Recovered node "期末自評總結" from @clean index.html</vh>
<v t="leo.20170114173925.325"><vh>old:期末自評總結</vh></v>
<v t="leo.20170114173925.326"><vh>new:期末自評總結</vh></v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="amd.20151215170031.1"></t>
<t tx="amd.20151215170117.1"></t>
<t tx="amd.20151215170221.1"></t>
<t tx="amd.20151215170350.1"></t>
<t tx="amd.20151215180106.1"></t>
<t tx="amd.20151216001126.1">@language md
Title: 文章標題 (請注意各文章的標題不可相同, 比較保險的作法是冠上四個學號尾碼)
Date: 2016-09-2 12:00
Category: 類別
Tags: 標籤
Author: yen

這裡放入文章摘要

&lt;!-- PELICAN_END_SUMMARY --&gt;

這裡為文章主要內容

程式碼

&lt;pre class="brush: python;"&gt;
print("hello")
&lt;/pre&gt;</t>
<t tx="amd.20160106093454.1"></t>
<t tx="amd.20160106094754.1"></t>
<t tx="amd.20160106094829.1"></t>
<t tx="amd.20160106095324.1"></t>
<t tx="amd.20160727114506.1"></t>
<t tx="amd.20160921213353.1"></t>
<t tx="leo.20151212173315.1"></t>
<t tx="leo.20151212173315.2">QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    background-color: #ffffec; /* Leo's traditional tree color */
    selection-color: black; /* was white */
    selection-background-color: lightgrey;
    /* font-family: SansSerif; */
    /*font-family: DejaVu Sans Mono;*/
    font-family:YaHei Mono;
    /* 標題字型大小設定 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    background-color: cornsilk;
    selection-color: white;
    selection-background-color: blue;
    /*font-family: DejaVu Sans Mono;*/    
    font-family:YaHei Mono;
    /* 沒有特別對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The log panes */
QTextEdit {
    background-color: #f2fdff;
    selection-color: red;
    selection-background-color: blue;
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* log font 大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The body pane */
QTextEdit#richTextEdit {
    background-color: #fdf5f5; /* A kind of pink. */
    selection-color: white;
    selection-background-color: red;
    /*font-family: DejaVu Sans Mono;*/
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* 內文字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLabel {
    font-family:YaHei Mono;'CherryPy', 'pytz', 'mako', 'beautifulsoup4', 'pymysql', 'peewee'
    /* 下方的 Minibuffer 標題字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/* Editor labels */
QLineEdit#editorLabel {
    background-color: #ffffec;
    font-family:YaHei Mono;
    /* 沒有直接對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
    border: 2px;
    margin: 2px;
}</t>
<t tx="leo.20151212173315.3">horizontal: body pane to the left
vertical: body pane on the botton</t>
<t tx="leo.20151213085727.1">@language python
import os
#os.system("pelican content -o output -s local_publishconf.py -t theme/pelican-bootstrap3")
os.system("pelican content -o blog -s local_publishconf.py")
g.es("admin pelican 近端執行完畢")


</t>
<t tx="leo.20151213173830.1"></t>
<t tx="leo.20151213230723.1"></t>
<t tx="leo.20151213230729.1">利用

&lt;!-- PELICAN_END_SUMMARY --&gt;

來界定 Summary 摘要內容

前提, 必須設定 

PLUGIN_PATHS = ['plugin']

與

PLUGINS = ['liquid_tags.notebook', 'summary']

並且從 https://github.com/getpelican/pelican-plugins

取得 summary plugin</t>
<t tx="leo.20151213230957.1"># 設定網誌以 md 檔案建立的 file system date 為準, 無需自行設定

DEFAULT_DATE = 'fs'</t>
<t tx="leo.20161013190948.1">@language html
&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;title&gt;
redirecting ....
&lt;/title&gt;
&lt;head&gt;
&lt;meta http-equiv="refresh" content="0; url=https://mdecourse.github.io/2016fallcadpa/" /&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;/body&gt;
&lt;/html&gt;</t>
<t tx="leo.20161014111031.1">@language xml
@tabwidth -4
@others
</t>
<t tx="leo.20161014111031.10">					&lt;h2&gt;筆記&lt;/h2&gt;
			
@others
				
				
				&lt;section&gt;
					&lt;p&gt;作業3&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/JFKJpplaqDs" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;p&gt;作業4&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/QPBiOIqfW28" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				&lt;/section&gt;

				&lt;section&gt;
</t>
<t tx="leo.20161014111031.11">  &lt;p&gt;第三週 proxy設定:proxy.mde.tw 通訊阜:3128 去聲音指令:ffmpeg.exe -i 檔名 -c copy -an out.mp4 字幕指令:ffmpeg.exe -i out.mp4 -vf subtitles=in.srt out2.mp4 安裝pelican指令:pip install pelican
  &lt;p&gt;第四週 刪除指令:git rm -rf 下載分支內的東西:git submodule update --init --recursive 子模組的對應版本更新到目前最新提交:git submodule foreach "(git checkout gh-pages; git pull)"
				
				&lt;/section&gt;

</t>
<t tx="leo.20161014111031.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;
</t>
<t tx="leo.20161014111031.24">					&lt;p&gt;這一次我們這組整個討論下來,覺得這一次的作業比較複雜一點但,在這一次又有學到新的知識,又得到了一些還沒學過的能力&lt;p&gt;
@others
</t>
<t tx="leo.20161014111031.25">		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;
@others
</t>
<t tx="leo.20161014111031.26">
		&lt;script&gt;
			// More info https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,
				transition: 'slide', // none/fade/slide/convex/concave/zoom
				// More info https://github.com/hakimel/reveal.js#dependencies
				dependencies: [
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true }
				]
			});
		&lt;/script&gt;

	&lt;/body&gt;
</t>
<t tx="leo.20161014111031.27">@others
</t>
<t tx="leo.20161014111031.28"></t>
<t tx="leo.20161014111031.3">
	&lt;head&gt;
		&lt;meta charset="utf-8"&gt;

		&lt;title&gt;reveal.js – The HTML Presentation Framework&lt;/title&gt;

</t>
<t tx="leo.20161014111031.37">@others
</t>
<t tx="leo.20161014111031.38">@others
</t>
<t tx="leo.20161014111031.39"></t>
<t tx="leo.20161014111031.4">		&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
@others
</t>
<t tx="leo.20161014111031.40">@others
</t>
<t tx="leo.20161014111031.41">@others
</t>
<t tx="leo.20161014111031.42"></t>
<t tx="leo.20161014111031.43">@others
</t>
<t tx="leo.20161014111031.44"></t>
<t tx="leo.20161014111031.5">		&lt;meta name="author" content="Hakim El Hattab"&gt;
@others
</t>
<t tx="leo.20161014111031.6">@others
</t>
<t tx="leo.20161014111031.7">@others

		&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;

		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;

		&lt;!-- Theme used for syntax highlighting of code --&gt;
		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;

		&lt;!-- Printing and PDF exports --&gt;
		&lt;script&gt;
			var link = document.createElement( 'link' );
			link.rel = 'stylesheet';
			link.type = 'text/css';
			link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
			document.getElementsByTagName( 'head' )[0].appendChild( link );
		&lt;/script&gt;

		&lt;!--[if lt IE 9]&gt;
		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
		&lt;![endif]--&gt;
	&lt;/head&gt;

	&lt;body&gt;

		&lt;div class="reveal"&gt;

			&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
			&lt;div class="slides"&gt;
				&lt;section&gt;
					&lt;h1&gt;40423201 黃上芸 計算機程式課程&lt;/h1&gt;
					&lt;h3&gt;The HTML Presentation Framework&lt;/h3&gt;
					&lt;p&gt;
						&lt;small&gt;Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;&lt;/small&gt;
					&lt;/p&gt;
                    &lt;a href="blog/index.html"&gt;blog&lt;/a&gt;
				&lt;/section&gt;
				
				&lt;section&gt;
				&lt;p&gt;筆記:1.創2016fallcadp_hw 將README打勾 格式:python 加密:agpl 新增gh-pages分支 進入setting 點branches 將master變更為gh-pages 點update 
					2.git clone 2016fallcadp_hw cd 2016fallcadp_hw git branch git checkout gh-pages git branch(再次檢查) 
					3.創 學號.github.io 將README打勾 格式:python 加密:agpl 點選create new file 打入index.html 點commit new file
					4.創 2016fallcadp_bg100(組別) 將2016fallcadp_bg100 clone下來 2016fallcadp_bg100 git branch git checkout gh-pages git branch(再次檢查) 將自己的2016fallcadp_hw clone網址複製 git submodule add -b gh-pages 網址 學號 git staus(檢查) 依序將隊友的資料夾加入 git add -A git commit -m "名稱" git push origin gh-pages
 &lt;/p&gt;
				&lt;/section&gt;
		
                               &lt;section&gt;
					&lt;h4&gt;作業1&lt;/h4&gt;
					&lt;iframe src="https://player.vimeo.com/video/185818182" width="640" height="400" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
			
                              &lt;/section&gt;
				
                               &lt;section&gt;
					&lt;h2&gt;這一次的作業我拍好影片,但是我借用德威的VIMEO上傳的時候德威忘記登出所以就直接借用他的了,我們這組是一起討論後最後才成功畫出作品的,很喜歡團隊合作的感覺,蠻有成就感的雖然在畫的時候失敗了一次又一次哈哈&lt;/h2&gt;
				
                              &lt;/section&gt;
                              
				&lt;!-- Example of nested vertical slides --&gt;
				&lt;section&gt;
					&lt;section&gt;
						&lt;p&gt;作業2&lt;/p&gt;
					&lt;iframe src="https://player.vimeo.com/video/190123005" width="640" height="306" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
				
						
</t>
<t tx="leo.20161014111031.8">
		&lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
		&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;
</t>
<t tx="leo.20161014111031.9">					
@others
					&lt;h2&gt;心得&lt;/h2&gt;
</t>
<t tx="leo.20161103232830.1">@others
</t>
<t tx="leo.20161103232830.2">@others
</t>
<t tx="leo.20161103232830.3"></t>
<t tx="leo.20161103232832.1">@others
</t>
<t tx="leo.20161103232832.2">@others
</t>
<t tx="leo.20161103232832.3"></t>
<t tx="leo.20161103233616.1">@others
</t>
<t tx="leo.20161103233616.2">@others
</t>
<t tx="leo.20161103233616.3"></t>
<t tx="leo.20161104010025.1">					&lt;/section&gt;
					
@others
				&lt;section&gt;
			
			&lt;h2&gt;心得&lt;/h2&gt;
				&lt;p&gt;在試用了老師所介紹的兩套軟體-SolveSpace 和 Onshape後 覺得Onshape較SolveSpace好用，而Onshape和我們常用的soildwork還滿像的 所以用起來比較習慣。SolveSpace沒一些快速指令，每執行完一項功能，就要重新點選，覺得比較麻煩一點!!&lt;/p&gt;
						
					
					&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;筆記&lt;/h2&gt;
						&lt;p&gt;第二週 1.radinsed半徑 2.diameter直徑 3.place放置 4.symmetrically對稱 5.lnitially開始 6.oriented定位 7.axes軸 8.indicated表示 9.respectively分別 10.parallel平行 11.extruding長出 12.automatically自動 13.coincident一模一樣 14.constraint約束 15.horizontal橫 16.perpendicular垂直 17.step圖(格式)
                                                &lt;p&gt;錄影工具:sharex 1.paths 2.task → screen recorder → options 開始錄製:shift+ print screen 射出成型軟體:moldex3d
                                                &lt;p&gt;作業 成品影片:https://vimeo.com/185115914
					&lt;/p&gt;
					
				&lt;/section&gt;

				&lt;section&gt;
</t>
<t tx="leo.20161104010025.2">					&lt;section&gt;
				
					&lt;/section&gt;
					&lt;section&gt;
						&lt;h2&gt;Basement Level 2&lt;/h2&gt;
						&lt;p&gt;That's it, time to go back up.&lt;/p&gt;
						&lt;br&gt;
						&lt;a href="#/2"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
				&lt;/section&gt;

</t>
<t tx="leo.20161104010248.1">				&lt;/section&gt;
@others
				&lt;/div&gt;

		&lt;/div&gt;

		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
</t>
<t tx="leo.20161104010248.2">
</t>
<t tx="leo.20161104010457.1">@others
</t>
<t tx="leo.20161104010457.2"></t>
<t tx="leo.20161104010537.1">@others
</t>
<t tx="leo.20161104010537.2"></t>
<t tx="leo.20161104010854.1">@others
</t>
<t tx="leo.20161104010854.2"></t>
<t tx="leo.20161104011343.1">@others
</t>
<t tx="leo.20161104011343.2"></t>
<t tx="leo.20161104011407.1">@others
</t>
<t tx="leo.20161104011407.2"></t>
<t tx="leo.20161104011701.1">@others
</t>
<t tx="leo.20161104011701.2"></t>
<t tx="leo.20161104203720.1">@others
</t>
<t tx="leo.20161104203720.2">@others
</t>
<t tx="leo.20161104203720.3"></t>
<t tx="leo.20161104203720.4">@others
</t>
<t tx="leo.20161104203720.5"></t>
<t tx="leo.20161115000909.1">@others
</t>
<t tx="leo.20161115000909.2">@others
</t>
<t tx="leo.20161115000909.3"></t>
<t tx="leo.20161115000909.4">@others
</t>
<t tx="leo.20161115000909.5"></t>
<t tx="leo.20161118111218.1">@language python
import os
import subprocess
import threading
import http.server, ssl

def domake():
    # build directory
    os.chdir("./../")
    server_address = ('localhost', 8443)
    httpd = http.server.HTTPServer(server_address, http.server.SimpleHTTPRequestHandler)
    httpd.socket = ssl.wrap_socket(httpd.socket,
                                   server_side=True,
                                   certfile='localhost.crt',
                                   keyfile='localhost.key',
                                   ssl_version=ssl.PROTOCOL_TLSv1)
    print("8443 https server started")
    httpd.serve_forever()

# 利用執行緒執行 https 伺服器
make = threading.Thread(target=domake)
make.start()</t>
<t tx="leo.20161124210839.1">@others
</t>
<t tx="leo.20161124210839.2">@others
</t>
<t tx="leo.20161124210839.3"></t>
<t tx="leo.20161124210839.4">@others
</t>
<t tx="leo.20161124210839.5"></t>
<t tx="leo.20161124210841.1">@others
</t>
<t tx="leo.20161124210841.2">@others
</t>
<t tx="leo.20161124210841.3"></t>
<t tx="leo.20161124210841.4">@others
</t>
<t tx="leo.20161124210841.5"></t>
<t tx="leo.20161209165346.1">@others
</t>
<t tx="leo.20161209165346.2">@others
</t>
<t tx="leo.20161209165346.3"></t>
<t tx="leo.20161209165346.4">@others
</t>
<t tx="leo.20161209165346.5"></t>
<t tx="leo.20161209165348.1">@others
</t>
<t tx="leo.20161209165348.2">@others
</t>
<t tx="leo.20161209165348.3"></t>
<t tx="leo.20161209165348.4">@others
</t>
<t tx="leo.20161209165348.5"></t>
<t tx="leo.20161209165937.1">@others
</t>
<t tx="leo.20161209165937.2"></t>
<t tx="leo.20161209165942.1">@others
</t>
<t tx="leo.20161209165942.2"></t>
<t tx="leo.20161209174033.1">@others
</t>
<t tx="leo.20161209174033.2"></t>
<t tx="leo.20170101215257.1">@others
</t>
<t tx="leo.20170101215257.2">@others
</t>
<t tx="leo.20170101215257.3"></t>
<t tx="leo.20170101215257.4">@others
</t>
<t tx="leo.20170101215257.5"></t>
<t tx="leo.20170101215259.1">@others
</t>
<t tx="leo.20170101215259.2">@others
</t>
<t tx="leo.20170101215259.3"></t>
<t tx="leo.20170101215259.4">@others
</t>
<t tx="leo.20170101215259.5"></t>
<t tx="leo.20170101215301.1">@others
</t>
<t tx="leo.20170101215301.2">@others
</t>
<t tx="leo.20170101215301.3"></t>
<t tx="leo.20170101215301.4">@others
</t>
<t tx="leo.20170101215301.5"></t>
<t tx="leo.20170112140710.1">@others
</t>
<t tx="leo.20170112140710.2">@others
</t>
<t tx="leo.20170112140710.3"></t>
<t tx="leo.20170112140710.4">@others
</t>
<t tx="leo.20170112140710.5"></t>
<t tx="leo.20170113103445.1">@others
</t>
<t tx="leo.20170113103445.2">@others
</t>
<t tx="leo.20170113103445.3"></t>
<t tx="leo.20170113103445.4">@others
</t>
<t tx="leo.20170113103445.5"></t>
<t tx="leo.20170114173925.10">&lt;div class="reveal"&gt;
@others
&lt;/div&gt;

</t>
<t tx="leo.20170114173925.100">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170114173925.101">@others
</t>
<t tx="leo.20170114173925.102">(uncached) leo.20161104011343.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.103">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.104">@others
</t>
<t tx="leo.20170114173925.105">(uncached) leo.20161104011343.2
Diff...
+ ## 2016-10-14 第五週
+ 
</t>
<t tx="leo.20170114173925.106">## 2016-10-14 第五週

</t>
<t tx="leo.20170114173925.107"></t>
<t tx="leo.20170114173925.108">(uncached) leo.20161103232830.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.109">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.11">		&lt;meta name="author" content="Hakim El Hattab"&gt;
@others
</t>
<t tx="leo.20170114173925.110">@others
</t>
<t tx="leo.20170114173925.111">(uncached) leo.20161103232830.3
Diff...
+ ## 初步認識SolveSpace
+ 
+ &lt;iframe src="https://player.vimeo.com/video/190087085" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
+ 
+ 
</t>
<t tx="leo.20170114173925.112">## 初步認識SolveSpace

&lt;iframe src="https://player.vimeo.com/video/190087085" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;


</t>
<t tx="leo.20170114173925.113"></t>
<t tx="leo.20170114173925.114">(uncached) leo.20161103232832.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170114173925.115">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170114173925.116">@others
</t>
<t tx="leo.20170114173925.117">(uncached) leo.20161104011407.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.118">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.119">@others
</t>
<t tx="leo.20170114173925.12">(uncached) leo.20161014111031.6
Diff...
+ &lt;!-- Any section element inside of this container is displayed as a slide --&gt;
+ &lt;div class="slides"&gt;
  @others
+ &lt;/div&gt;
+ 
</t>
<t tx="leo.20170114173925.120">(uncached) leo.20161104011407.2
Diff...
+ ## 2016-10-21 第六週
+ 
</t>
<t tx="leo.20170114173925.121">## 2016-10-21 第六週

</t>
<t tx="leo.20170114173925.122"></t>
<t tx="leo.20170114173925.123">(uncached) leo.20161103232832.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.124">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.125">@others
</t>
<t tx="leo.20170114173925.126">(uncached) leo.20161103232832.3
Diff...
+ ## 解決子模組在對應上的問題
+ 
+ &lt;p&gt;因為之前的2016fallcadp_hw倉儲少複製了一些東西,刪除舊的倉儲後,重新做一個和之前倉儲同名的2016fallcadp_hw倉儲,但是在小組倉儲所連結的子模組,抓不到新倉儲連結,所以我們需要重新加入一次組員倉儲的資料&lt;/p&gt;
+ 
+ 
</t>
<t tx="leo.20170114173925.127">## 解決子模組在對應上的問題

&lt;p&gt;因為之前的2016fallcadp_hw倉儲少複製了一些東西,刪除舊的倉儲後,重新做一個和之前倉儲同名的2016fallcadp_hw倉儲,但是在小組倉儲所連結的子模組,抓不到新倉儲連結,所以我們需要重新加入一次組員倉儲的資料&lt;/p&gt;


</t>
<t tx="leo.20170114173925.128"></t>
<t tx="leo.20170114173925.129">(uncached) leo.20161103233616.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170114173925.13">&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;

</t>
<t tx="leo.20170114173925.130">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170114173925.131">@others
</t>
<t tx="leo.20170114173925.132">(uncached) leo.20161104011701.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.133">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.134">@others
</t>
<t tx="leo.20170114173925.135">(uncached) leo.20161104011701.2
Diff...
+ ## 2016-10-28 第七週
+ 
</t>
<t tx="leo.20170114173925.136">## 2016-10-28 第七週

</t>
<t tx="leo.20170114173925.137"></t>
<t tx="leo.20170114173925.138">(uncached) leo.20161103233616.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.139">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.14">@others
</t>
<t tx="leo.20170114173925.140">@others
</t>
<t tx="leo.20170114173925.141">(uncached) leo.20161103233616.3
Diff...
+ ## 使用Trace Point計算路徑
+ 
+ &lt;iframe src="https://player.vimeo.com/video/190090265" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
+ 
+ 
</t>
<t tx="leo.20170114173925.142">## 使用Trace Point計算路徑

&lt;iframe src="https://player.vimeo.com/video/190090265" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;


</t>
<t tx="leo.20170114173925.143"></t>
<t tx="leo.20170114173925.144">(uncached) leo.20161104203720.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170114173925.145">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170114173925.146">@others
</t>
<t tx="leo.20170114173925.147">(uncached) leo.20161104203720.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.148">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.149">@others
</t>
<t tx="leo.20170114173925.15">(uncached) leo.20161014111031.7
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
  
- 		&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;
  
- 		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
- 		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;
- 
- 		&lt;!-- Theme used for syntax highlighting of code --&gt;
- 		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;
- 
- 		&lt;!-- Printing and PDF exports --&gt;
- 		&lt;script&gt;
- 			var link = document.createElement( 'link' );
- 			link.rel = 'stylesheet';
- 			link.type = 'text/css';
- 			link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
- 			document.getElementsByTagName( 'head' )[0].appendChild( link );
- 		&lt;/script&gt;
- 
- 		&lt;!--[if lt IE 9]&gt;
- 		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
- 		&lt;![endif]--&gt;
- 	&lt;/head&gt;
- 
- 	&lt;body&gt;
- 
- 		&lt;div class="reveal"&gt;
- 
- 			&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
- 			&lt;div class="slides"&gt;
- 				&lt;section&gt;
- 					&lt;h1&gt;40423201 黃上芸 計算機程式課程&lt;/h1&gt;
- 					&lt;h3&gt;The HTML Presentation Framework&lt;/h3&gt;
- 					&lt;p&gt;
- 						&lt;small&gt;Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;&lt;/small&gt;
- 					&lt;/p&gt;
-                     &lt;a href="blog/index.html"&gt;blog&lt;/a&gt;
- 				&lt;/section&gt;
- 				
- 				&lt;section&gt;
- 				&lt;p&gt;筆記:1.創2016fallcadp_hw 將README打勾 格式:python 加密:agpl 新增gh-pages分支 進入setting 點branches 將master變更為gh-pages 點update 
- 					2.git clone 2016fallcadp_hw cd 2016fallcadp_hw git branch git checkout gh-pages git branch(再次檢查) 
- 					3.創 學號.github.io 將README打勾 格式:python 加密:agpl 點選create new file 打入index.html 點commit new file
- 					4.創 2016fallcadp_bg100(組別) 將2016fallcadp_bg100 clone下來 2016fallcadp_bg100 git branch git checkout gh-pages git branch(再次檢查) 將自己的2016fallcadp_hw clone網址複製 git submodule add -b gh-pages 網址 學號 git staus(檢查) 依序將隊友的資料夾加入 git add -A git commit -m "名稱" git push origin gh-pages
-  &lt;/p&gt;
- 				&lt;/section&gt;
- 		
-                                &lt;section&gt;
- 					&lt;h4&gt;作業1&lt;/h4&gt;
- 					&lt;iframe src="https://player.vimeo.com/video/185818182" width="640" height="400" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
- 			
-                               &lt;/section&gt;
- 				
-                                &lt;section&gt;
- 					&lt;h2&gt;這一次的作業我拍好影片,但是我借用德威的VIMEO上傳的時候德威忘記登出所以就直接借用他的了,我們這組是一起討論後最後才成功畫出作品的,很喜歡團隊合作的感覺,蠻有成就感的雖然在畫的時候失敗了一次又一次哈哈&lt;/h2&gt;
- 				
-                               &lt;/section&gt;
-                               
- 				&lt;!-- Example of nested vertical slides --&gt;
- 				&lt;section&gt;
- 					&lt;section&gt;
- 						&lt;p&gt;作業2&lt;/p&gt;
- 					&lt;iframe src="https://player.vimeo.com/video/190123005" width="640" height="306" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
- 				
  						
</t>
<t tx="leo.20170114173925.150">(uncached) leo.20161104203720.3
Diff...
+ ## 2016-11-04 第八週
+ 
</t>
<t tx="leo.20170114173925.151">## 2016-11-04 第八週

</t>
<t tx="leo.20170114173925.152"></t>
<t tx="leo.20170114173925.153">(uncached) leo.20161104203720.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.154">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.155">@others
</t>
<t tx="leo.20170114173925.156">(uncached) leo.20161104203720.5
Diff...
+ ## 期中課程評分
+ 
+ &lt;p&gt;&lt;a href="http://pygroup-ag100.rhcloud.com"&gt;評分系統&lt;/a&gt;&lt;/p&gt;
+ 
</t>
<t tx="leo.20170114173925.157">## 期中課程評分

&lt;p&gt;&lt;a href="http://pygroup-ag100.rhcloud.com"&gt;評分系統&lt;/a&gt;&lt;/p&gt;

</t>
<t tx="leo.20170114173925.158"></t>
<t tx="leo.20170114173925.159">(uncached) leo.20161115000909.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170114173925.16">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.160">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170114173925.161">@others
</t>
<t tx="leo.20170114173925.162">(uncached) leo.20161115000909.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.163">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.164">@others
</t>
<t tx="leo.20170114173925.165">(uncached) leo.20161115000909.3
Diff...
+ ## 2016-11-18 第九週
+ 
</t>
<t tx="leo.20170114173925.166">## 2016-11-18 第九週

</t>
<t tx="leo.20170114173925.167"></t>
<t tx="leo.20170114173925.168">(uncached) leo.20161115000909.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.169">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.17">@others

		&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;

		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;

		&lt;!-- Theme used for syntax highlighting of code --&gt;
		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;

		&lt;!-- Printing and PDF exports --&gt;
		&lt;script&gt;
			var link = document.createElement( 'link' );
			link.rel = 'stylesheet';
			link.type = 'text/css';
			link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
			document.getElementsByTagName( 'head' )[0].appendChild( link );
		&lt;/script&gt;

		&lt;!--[if lt IE 9]&gt;
		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
		&lt;![endif]--&gt;
	&lt;/head&gt;

	&lt;body&gt;

		&lt;div class="reveal"&gt;

			&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
			&lt;div class="slides"&gt;
				&lt;section&gt;
					&lt;h1&gt;40423201 黃上芸 計算機程式課程&lt;/h1&gt;
					&lt;h3&gt;The HTML Presentation Framework&lt;/h3&gt;
					&lt;p&gt;
						&lt;small&gt;Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;&lt;/small&gt;
					&lt;/p&gt;
                    &lt;a href="blog/index.html"&gt;blog&lt;/a&gt;
				&lt;/section&gt;
				
				&lt;section&gt;
				&lt;p&gt;筆記:1.創2016fallcadp_hw 將README打勾 格式:python 加密:agpl 新增gh-pages分支 進入setting 點branches 將master變更為gh-pages 點update 
					2.git clone 2016fallcadp_hw cd 2016fallcadp_hw git branch git checkout gh-pages git branch(再次檢查) 
					3.創 學號.github.io 將README打勾 格式:python 加密:agpl 點選create new file 打入index.html 點commit new file
					4.創 2016fallcadp_bg100(組別) 將2016fallcadp_bg100 clone下來 2016fallcadp_bg100 git branch git checkout gh-pages git branch(再次檢查) 將自己的2016fallcadp_hw clone網址複製 git submodule add -b gh-pages 網址 學號 git staus(檢查) 依序將隊友的資料夾加入 git add -A git commit -m "名稱" git push origin gh-pages
 &lt;/p&gt;
				&lt;/section&gt;
		
                               &lt;section&gt;
					&lt;h4&gt;作業1&lt;/h4&gt;
					&lt;iframe src="https://player.vimeo.com/video/185818182" width="640" height="400" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
			
                              &lt;/section&gt;
				
                               &lt;section&gt;
					&lt;h2&gt;這一次的作業我拍好影片,但是我借用德威的VIMEO上傳的時候德威忘記登出所以就直接借用他的了,我們這組是一起討論後最後才成功畫出作品的,很喜歡團隊合作的感覺,蠻有成就感的雖然在畫的時候失敗了一次又一次哈哈&lt;/h2&gt;
				
                              &lt;/section&gt;
                              
				&lt;!-- Example of nested vertical slides --&gt;
				&lt;section&gt;
					&lt;section&gt;
						&lt;p&gt;作業2&lt;/p&gt;
					&lt;iframe src="https://player.vimeo.com/video/190123005" width="640" height="306" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
				
						
</t>
<t tx="leo.20170114173925.170">@others
</t>
<t tx="leo.20170114173925.171">(uncached) leo.20161115000909.5
Diff...
+ ## 期中自我評分
+ 
+ &lt;p&gt;&lt;a href="http://mde.tw/2016fallcadp/blog/2016fall-ji-jie-she-ji-zhu-ti-jiao-xue.html"&gt;檢查自己的連結是否正確&lt;/a&gt;&lt;/p&gt;
+ 
</t>
<t tx="leo.20170114173925.172">## 期中自我評分

&lt;p&gt;&lt;a href="http://mde.tw/2016fallcadp/blog/2016fall-ji-jie-she-ji-zhu-ti-jiao-xue.html"&gt;檢查自己的連結是否正確&lt;/a&gt;&lt;/p&gt;

</t>
<t tx="leo.20170114173925.173"></t>
<t tx="leo.20170114173925.174">(uncached) leo.20161124210839.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170114173925.175">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170114173925.176">@others
</t>
<t tx="leo.20170114173925.177">(uncached) leo.20161124210839.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.178">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.179">@others
</t>
<t tx="leo.20170114173925.18">(uncached) leo.20161014111031.8
Diff...
+ ## 2016Fall 電腦輔助設計實習課程
+ ### 虎科大機械設計工程系
+ ### 設計二乙
+ ### 40423226
+ ### 胡 原 愷
  
- 		&lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
- 		&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;
+ &lt;small&gt;
+ [個人網誌](https://40423226.github.io/2016fallcadp_hw/blog/)
+ &lt;/small&gt;
</t>
<t tx="leo.20170114173925.180">(uncached) leo.20161124210839.3
Diff...
+ ## 2016-11-18 第十週
+ 
</t>
<t tx="leo.20170114173925.181">## 2016-11-18 第十週

</t>
<t tx="leo.20170114173925.182"></t>
<t tx="leo.20170114173925.183">(uncached) leo.20161124210839.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.184">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.185">@others
</t>
<t tx="leo.20170114173925.186">(uncached) leo.20161124210839.5
Diff...
+ ## Solvespace 平面四連桿機構模擬
+ 
+ &lt;iframe src="https://player.vimeo.com/video/192930481" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
+ 
</t>
<t tx="leo.20170114173925.187">## Solvespace 平面四連桿機構模擬

&lt;iframe src="https://player.vimeo.com/video/192930481" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;

</t>
<t tx="leo.20170114173925.188"></t>
<t tx="leo.20170114173925.189">(uncached) leo.20161124210841.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170114173925.19">## 2016Fall 電腦輔助設計實習課程
### 虎科大機械設計工程系
### 設計二乙
### 40423226
### 胡 原 愷

&lt;small&gt;
[個人網誌](https://40423226.github.io/2016fallcadp_hw/blog/)
&lt;/small&gt;
</t>
<t tx="leo.20170114173925.190">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170114173925.191">@others
</t>
<t tx="leo.20170114173925.192">(uncached) leo.20161124210841.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.193">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.194">@others
</t>
<t tx="leo.20170114173925.195">(uncached) leo.20161124210841.3
Diff...
+ ## 2016-11-25 第十一週
+ 
</t>
<t tx="leo.20170114173925.196">## 2016-11-25 第十一週

</t>
<t tx="leo.20170114173925.197"></t>
<t tx="leo.20170114173925.198">(uncached) leo.20161124210841.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.199">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.2"></t>
<t tx="leo.20170114173925.20">
		&lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
		&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;
</t>
<t tx="leo.20170114173925.200">@others
</t>
<t tx="leo.20170114173925.201">(uncached) leo.20161124210841.5
Diff...
+ ## 虎科大36週年校慶</t>
<t tx="leo.20170114173925.202">## 虎科大36週年校慶</t>
<t tx="leo.20170114173925.203"></t>
<t tx="leo.20170114173925.204">(uncached) leo.20161209165346.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170114173925.205">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170114173925.206">@others
</t>
<t tx="leo.20170114173925.207">(uncached) leo.20161209165346.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.208">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.209">@others
</t>
<t tx="leo.20170114173925.21">(uncached) leo.20161014111031.9
Diff...
- 					
+ &lt;section&gt;
  @others
- 					&lt;h2&gt;心得&lt;/h2&gt;
+ &lt;/section&gt;
</t>
<t tx="leo.20170114173925.210">(uncached) leo.20161209165346.3
Diff...
+ ## 2016-12-02 第十二週
+ 
</t>
<t tx="leo.20170114173925.211">## 2016-12-02 第十二週

</t>
<t tx="leo.20170114173925.212"></t>
<t tx="leo.20170114173925.213">(uncached) leo.20161209174033.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.214">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.215">@others
</t>
<t tx="leo.20170114173925.216">(uncached) leo.20161209174033.2
Diff...
+ ## 利用SolveSpace存html檔
+ 
+ &lt;iframe src="https://player.vimeo.com/video/194948275" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170114173925.217">## 利用SolveSpace存html檔

&lt;iframe src="https://player.vimeo.com/video/194948275" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170114173925.218"></t>
<t tx="leo.20170114173925.219">(uncached) leo.20161209165346.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.22">&lt;section&gt;
@others
&lt;/section&gt;
</t>
<t tx="leo.20170114173925.220">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.221">@others
</t>
<t tx="leo.20170114173925.222">(uncached) leo.20161209165346.5
Diff...
+ ## Cube
+ &lt;iframe src="https://player.vimeo.com/video/194943832" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170114173925.223">## Cube
&lt;iframe src="https://player.vimeo.com/video/194943832" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170114173925.224"></t>
<t tx="leo.20170114173925.225">(uncached) leo.20161209165937.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.226">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.227">@others
</t>
<t tx="leo.20170114173925.228">(uncached) leo.20161209165937.2
Diff...
+ ## Strut
+ 
+ &lt;iframe src="https://player.vimeo.com/video/194943838" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170114173925.229">## Strut

&lt;iframe src="https://player.vimeo.com/video/194943838" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170114173925.23">					
@others
					&lt;h2&gt;心得&lt;/h2&gt;
</t>
<t tx="leo.20170114173925.230"></t>
<t tx="leo.20170114173925.231">(uncached) leo.20161209165942.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.232">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.233">@others
</t>
<t tx="leo.20170114173925.234">(uncached) leo.20161209165942.2
Diff...
+ ## 組合
+ 
+ &lt;iframe src="https://player.vimeo.com/video/194943848" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170114173925.235">## 組合

&lt;iframe src="https://player.vimeo.com/video/194943848" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170114173925.236"></t>
<t tx="leo.20170114173925.237">(uncached) leo.20161209165348.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170114173925.238">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170114173925.239">@others
</t>
<t tx="leo.20170114173925.24">(uncached) leo.20161104010025.1
Diff...
- 					&lt;/section&gt;
- 					
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
- 				&lt;section&gt;
? ----
+ &lt;/section&gt;
?  +
+ 
+ 
- 			
- 			&lt;h2&gt;心得&lt;/h2&gt;
- 				&lt;p&gt;在試用了老師所介紹的兩套軟體-SolveSpace 和 Onshape後 覺得Onshape較SolveSpace好用，而Onshape和我們常用的soildwork還滿像的 所以用起來比較習慣。SolveSpace沒一些快速指令，每執行完一項功能，就要重新點選，覺得比較麻煩一點!!&lt;/p&gt;
  						
- 					
- 					&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;筆記&lt;/h2&gt;
- 						&lt;p&gt;第二週 1.radinsed半徑 2.diameter直徑 3.place放置 4.symmetrically對稱 5.lnitially開始 6.oriented定位 7.axes軸 8.indicated表示 9.respectively分別 10.parallel平行 11.extruding長出 12.automatically自動 13.coincident一模一樣 14.constraint約束 15.horizontal橫 16.perpendicular垂直 17.step圖(格式)
-                                                 &lt;p&gt;錄影工具:sharex 1.paths 2.task → screen recorder → options 開始錄製:shift+ print screen 射出成型軟體:moldex3d
-                                                 &lt;p&gt;作業 成品影片:https://vimeo.com/185115914
- 					&lt;/p&gt;
- 					
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
</t>
<t tx="leo.20170114173925.240">(uncached) leo.20161209165348.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.241">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.242">@others
</t>
<t tx="leo.20170114173925.243">(uncached) leo.20161209165348.3
Diff...
+ ## 2016-12-09 第十三週
+ 
</t>
<t tx="leo.20170114173925.244">## 2016-12-09 第十三週

</t>
<t tx="leo.20170114173925.245"></t>
<t tx="leo.20170114173925.246">(uncached) leo.20161209165348.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.247">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.248">@others
</t>
<t tx="leo.20170114173925.249">(uncached) leo.20161209165348.5
Diff...
+ ## 遠端網誌無法更新
+ 
+ &lt;p&gt;近端利用瀏覽器檢查網誌是正常,但是遠端的網誌卻沒有更新,發現推上去的資料出現問題,GitHub還親自寄信給我&lt;/p&gt;</t>
<t tx="leo.20170114173925.25">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.250">## 遠端網誌無法更新

&lt;p&gt;近端利用瀏覽器檢查網誌是正常,但是遠端的網誌卻沒有更新,發現推上去的資料出現問題,GitHub還親自寄信給我&lt;/p&gt;</t>
<t tx="leo.20170114173925.251"></t>
<t tx="leo.20170114173925.252">(uncached) leo.20170101215257.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170114173925.253">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170114173925.254">@others
</t>
<t tx="leo.20170114173925.255">(uncached) leo.20170101215257.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.256">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.257">@others
</t>
<t tx="leo.20170114173925.258">(uncached) leo.20170101215257.3
Diff...
+ ## 2016-12-16 第十四週
+ 
</t>
<t tx="leo.20170114173925.259">## 2016-12-16 第十四週

</t>
<t tx="leo.20170114173925.26">					&lt;/section&gt;
					
@others
				&lt;section&gt;
			
			&lt;h2&gt;心得&lt;/h2&gt;
				&lt;p&gt;在試用了老師所介紹的兩套軟體-SolveSpace 和 Onshape後 覺得Onshape較SolveSpace好用，而Onshape和我們常用的soildwork還滿像的 所以用起來比較習慣。SolveSpace沒一些快速指令，每執行完一項功能，就要重新點選，覺得比較麻煩一點!!&lt;/p&gt;
						
					
					&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;筆記&lt;/h2&gt;
						&lt;p&gt;第二週 1.radinsed半徑 2.diameter直徑 3.place放置 4.symmetrically對稱 5.lnitially開始 6.oriented定位 7.axes軸 8.indicated表示 9.respectively分別 10.parallel平行 11.extruding長出 12.automatically自動 13.coincident一模一樣 14.constraint約束 15.horizontal橫 16.perpendicular垂直 17.step圖(格式)
                                                &lt;p&gt;錄影工具:sharex 1.paths 2.task → screen recorder → options 開始錄製:shift+ print screen 射出成型軟體:moldex3d
                                                &lt;p&gt;作業 成品影片:https://vimeo.com/185115914
					&lt;/p&gt;
					
				&lt;/section&gt;

				&lt;section&gt;
</t>
<t tx="leo.20170114173925.260"></t>
<t tx="leo.20170114173925.261">(uncached) leo.20170101215257.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.262">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.263">@others
</t>
<t tx="leo.20170114173925.264">(uncached) leo.20170101215257.5
Diff...
+ ## delta_printer
+ 
+ &lt;img src="data/solvespace/delta_printer_v2/delta_printer.png" width="800" /&gt;</t>
<t tx="leo.20170114173925.265">## delta_printer

&lt;img src="data/solvespace/delta_printer_v2/delta_printer.png" width="800" /&gt;</t>
<t tx="leo.20170114173925.266"></t>
<t tx="leo.20170114173925.267">(uncached) leo.20170101215259.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170114173925.268">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170114173925.269">@others
</t>
<t tx="leo.20170114173925.27">(uncached) leo.20161104010025.2
Diff...
+ ## 2016-09-16 第一週
- 					&lt;section&gt;
- 				
- 					&lt;/section&gt;
- 					&lt;section&gt;
- 						&lt;h2&gt;Basement Level 2&lt;/h2&gt;
- 						&lt;p&gt;That's it, time to go back up.&lt;/p&gt;
- 						&lt;br&gt;
- 						&lt;a href="#/2"&gt;
- 							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
- 						&lt;/a&gt;
- 					&lt;/section&gt;
- 				&lt;/section&gt;
  
</t>
<t tx="leo.20170114173925.270">(uncached) leo.20170101215259.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.271">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.272">@others
</t>
<t tx="leo.20170114173925.273">(uncached) leo.20170101215259.3
Diff...
+ ## 2016-12-23 第十五週
+ 
</t>
<t tx="leo.20170114173925.274">## 2016-12-23 第十五週

</t>
<t tx="leo.20170114173925.275"></t>
<t tx="leo.20170114173925.276">(uncached) leo.20170101215259.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.277">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.278">@others
</t>
<t tx="leo.20170114173925.279">(uncached) leo.20170101215259.5
Diff...
+ ## 整理目前為止上課的內容</t>
<t tx="leo.20170114173925.28">## 2016-09-16 第一週

</t>
<t tx="leo.20170114173925.280">## 整理目前為止上課的內容</t>
<t tx="leo.20170114173925.281"></t>
<t tx="leo.20170114173925.282">(uncached) leo.20170101215301.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170114173925.283">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170114173925.284">@others
</t>
<t tx="leo.20170114173925.285">(uncached) leo.20170101215301.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.286">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.287">@others
</t>
<t tx="leo.20170114173925.288">(uncached) leo.20170101215301.3
Diff...
+ ## 2016-12-30 第十六週
+ 
</t>
<t tx="leo.20170114173925.289">## 2016-12-30 第十六週

</t>
<t tx="leo.20170114173925.29">					&lt;section&gt;
				
					&lt;/section&gt;
					&lt;section&gt;
						&lt;h2&gt;Basement Level 2&lt;/h2&gt;
						&lt;p&gt;That's it, time to go back up.&lt;/p&gt;
						&lt;br&gt;
						&lt;a href="#/2"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
				&lt;/section&gt;

</t>
<t tx="leo.20170114173925.290"></t>
<t tx="leo.20170114173925.291">(uncached) leo.20170101215301.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.292">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.293">@others
</t>
<t tx="leo.20170114173925.294">(uncached) leo.20170101215301.5
Diff...
+ ## 繪製 Mechanism Tutorial
+ 
+ &lt;img src="data/image/Mechanism Tutorial.png" width="800" /&gt;</t>
<t tx="leo.20170114173925.295">## 繪製 Mechanism Tutorial

&lt;img src="data/image/Mechanism Tutorial.png" width="800" /&gt;</t>
<t tx="leo.20170114173925.296"></t>
<t tx="leo.20170114173925.297">(uncached) leo.20170112140710.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170114173925.298">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170114173925.299">@others
</t>
<t tx="leo.20170114173925.3">(uncached) leo.20161014111031.3
Diff...
+ &lt;head&gt;
+     &lt;meta charset="utf-8"&gt;
+ &lt;title&gt;
+ 2016 Fall 電腦輔助設計實習課程
+ &lt;/title&gt;
+     &lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
+     &lt;meta name="author" content="Hakim El Hattab"&gt;
+     
+     &lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
+     &lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;
+     
+     &lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;
+     
+     &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
+     &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;
+     
+     &lt;!-- Theme used for syntax highlighting of code --&gt;
+     &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;
  
- 	&lt;head&gt;
- 		&lt;meta charset="utf-8"&gt;
+     &lt;!-- Printing and PDF exports --&gt;
+     &lt;script&gt;
+         var link = document.createElement( 'link' );
+         link.rel = 'stylesheet';
+         link.type = 'text/css';
+         link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
+         document.getElementsByTagName( 'head' )[0].appendChild( link );
+     &lt;/script&gt;
  
- 		&lt;title&gt;reveal.js – The HTML Presentation Framework&lt;/title&gt;
+     &lt;!--[if lt IE 9]&gt;
+     &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
+     &lt;![endif]--&gt;
+ &lt;/head&gt;
  
</t>
<t tx="leo.20170114173925.30">(uncached) leo.20161014111031.10
Diff...
- 					&lt;h2&gt;筆記&lt;/h2&gt;
- 			
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
- 				
- 				
- 				&lt;section&gt;
- 					&lt;p&gt;作業3&lt;/p&gt;
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/JFKJpplaqDs" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
- 				&lt;/section&gt;
? ----
+ &lt;/section&gt;
  
- 				&lt;section&gt;
- 					&lt;p&gt;作業4&lt;/p&gt;
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/QPBiOIqfW28" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
- 				&lt;/section&gt;
  
- 				&lt;section&gt;
+ 						
</t>
<t tx="leo.20170114173925.300">(uncached) leo.20170112140710.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.301">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.302">@others
</t>
<t tx="leo.20170114173925.303">(uncached) leo.20170112140710.3
Diff...
+ ## 2017-01-06 第十七週
+ 
</t>
<t tx="leo.20170114173925.304">## 2017-01-06 第十七週

</t>
<t tx="leo.20170114173925.305"></t>
<t tx="leo.20170114173925.306">(uncached) leo.20170112140710.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.307">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.308">@others
</t>
<t tx="leo.20170114173925.309">(uncached) leo.20170112140710.5
Diff...
+ ## 利用約束條件,使機構作相對運動
+ 
+ &lt;iframe src="https://player.vimeo.com/video/199112247" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170114173925.31">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.310">## 利用約束條件,使機構作相對運動

&lt;iframe src="https://player.vimeo.com/video/199112247" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170114173925.311"></t>
<t tx="leo.20170114173925.312">(uncached) leo.20170113103445.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170114173925.313">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170114173925.314">@others
</t>
<t tx="leo.20170114173925.315">(uncached) leo.20170113103445.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.316">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.317">@others
</t>
<t tx="leo.20170114173925.318">(uncached) leo.20170113103445.3
Diff...
+ ## 2017-01-13 第十八週
+ 
</t>
<t tx="leo.20170114173925.319">## 2017-01-13 第十八週

</t>
<t tx="leo.20170114173925.32">					&lt;h2&gt;筆記&lt;/h2&gt;
			
@others
				
				
				&lt;section&gt;
					&lt;p&gt;作業3&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/JFKJpplaqDs" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;p&gt;作業4&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/QPBiOIqfW28" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				&lt;/section&gt;

				&lt;section&gt;
</t>
<t tx="leo.20170114173925.320"></t>
<t tx="leo.20170114173925.321">(uncached) leo.20170113103445.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.322">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.323">@others
</t>
<t tx="leo.20170114173925.324">(uncached) leo.20170113103445.5
Diff...
+ ## 2016 Fall 電腦輔助設計與實習期末自評總結</t>
<t tx="leo.20170114173925.325">## 2016 Fall 電腦輔助設計與實習期末自評總結</t>
<t tx="leo.20170114173925.326"></t>
<t tx="leo.20170114173925.33">(uncached) leo.20161014111031.11
Diff...
+ 中秋連假
-   &lt;p&gt;第三週 proxy設定:proxy.mde.tw 通訊阜:3128 去聲音指令:ffmpeg.exe -i 檔名 -c copy -an out.mp4 字幕指令:ffmpeg.exe -i out.mp4 -vf subtitles=in.srt out2.mp4 安裝pelican指令:pip install pelican
-   &lt;p&gt;第四週 刪除指令:git rm -rf 下載分支內的東西:git submodule update --init --recursive 子模組的對應版本更新到目前最新提交:git submodule foreach "(git checkout gh-pages; git pull)"
- 				
- 				&lt;/section&gt;
  
</t>
<t tx="leo.20170114173925.34">中秋連假

</t>
<t tx="leo.20170114173925.35">  &lt;p&gt;第三週 proxy設定:proxy.mde.tw 通訊阜:3128 去聲音指令:ffmpeg.exe -i 檔名 -c copy -an out.mp4 字幕指令:ffmpeg.exe -i out.mp4 -vf subtitles=in.srt out2.mp4 安裝pelican指令:pip install pelican
  &lt;p&gt;第四週 刪除指令:git rm -rf 下載分支內的東西:git submodule update --init --recursive 子模組的對應版本更新到目前最新提交:git submodule foreach "(git checkout gh-pages; git pull)"
				
				&lt;/section&gt;

</t>
<t tx="leo.20170114173925.36">(uncached) leo.20161014111031.24
Diff...
- 					&lt;p&gt;這一次我們這組整個討論下來,覺得這一次的作業比較複雜一點但,在這一次又有學到新的知識,又得到了一些還沒學過的能力&lt;p&gt;
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170114173925.37">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170114173925.38">					&lt;p&gt;這一次我們這組整個討論下來,覺得這一次的作業比較複雜一點但,在這一次又有學到新的知識,又得到了一些還沒學過的能力&lt;p&gt;
@others
</t>
<t tx="leo.20170114173925.39">(uncached) leo.20161104010248.1
Diff...
- 				&lt;/section&gt;
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
- 				&lt;/div&gt;
+     &lt;/script&gt;
+ &lt;/section&gt;
  
- 		&lt;/div&gt;
  
- 		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
+ 						
</t>
<t tx="leo.20170114173925.4">&lt;head&gt;
    &lt;meta charset="utf-8"&gt;
&lt;title&gt;
2016 Fall 電腦輔助設計實習課程
&lt;/title&gt;
    &lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
    &lt;meta name="author" content="Hakim El Hattab"&gt;
    
    &lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
    &lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;
    
    &lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;
    
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;
    
    &lt;!-- Theme used for syntax highlighting of code --&gt;
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
&lt;/head&gt;

</t>
<t tx="leo.20170114173925.40">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.41">				&lt;/section&gt;
@others
				&lt;/div&gt;

		&lt;/div&gt;

		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
</t>
<t tx="leo.20170114173925.42">(uncached) leo.20161104010248.2
Diff...
+ ## 2016-09-23 第二週
  
</t>
<t tx="leo.20170114173925.43">## 2016-09-23 第二週

</t>
<t tx="leo.20170114173925.44">
</t>
<t tx="leo.20170114173925.45">(uncached) leo.20161014111031.25
Diff...
- 		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.46">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.47">		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;
@others
</t>
<t tx="leo.20170114173925.48">(uncached) leo.20161014111031.26
Diff...
+ ## 建立
+ ## 40423226.github.io名稱的倉儲
  
+ &lt;iframe src="https://player.vimeo.com/video/190063679" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
- 		&lt;script&gt;
- 			// More info https://github.com/hakimel/reveal.js#configuration
- 			Reveal.initialize({
- 				controls: true,
- 				progress: true,
- 				history: true,
- 				center: true,
- 				transition: 'slide', // none/fade/slide/convex/concave/zoom
- 				// More info https://github.com/hakimel/reveal.js#dependencies
- 				dependencies: [
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true }
- 				]
- 			});
- 		&lt;/script&gt;
  
- 	&lt;/body&gt;
+ 
</t>
<t tx="leo.20170114173925.49">## 建立
## 40423226.github.io名稱的倉儲

&lt;iframe src="https://player.vimeo.com/video/190063679" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;


</t>
<t tx="leo.20170114173925.5">
	&lt;head&gt;
		&lt;meta charset="utf-8"&gt;

		&lt;title&gt;reveal.js – The HTML Presentation Framework&lt;/title&gt;

</t>
<t tx="leo.20170114173925.50">
		&lt;script&gt;
			// More info https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,
				transition: 'slide', // none/fade/slide/convex/concave/zoom
				// More info https://github.com/hakimel/reveal.js#dependencies
				dependencies: [
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true }
				]
			});
		&lt;/script&gt;

	&lt;/body&gt;
</t>
<t tx="leo.20170114173925.51">(uncached) leo.20161014111031.27
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.52">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.53">@others
</t>
<t tx="leo.20170114173925.54">(uncached) leo.20161014111031.28
Diff...
+ ## 把分支的預設值改為gh-pages
+ 
+ &lt;iframe src="https://player.vimeo.com/video/190064489" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170114173925.55">## 把分支的預設值改為gh-pages

&lt;iframe src="https://player.vimeo.com/video/190064489" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170114173925.56"></t>
<t tx="leo.20170114173925.57">(uncached) leo.20161014111031.37
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170114173925.58">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170114173925.59">@others
</t>
<t tx="leo.20170114173925.6">(uncached) leo.20161014111031.4
Diff...
- 		&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
+ &lt;body&gt;
  @others
+ &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
+ &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;
+ &lt;script&gt;
+         // More info https://github.com/hakimel/reveal.js#configuration
+         Reveal.initialize({
+             controls: true,
+             progress: true,
+             history: true,
+             center: true,
+ 
+             transition: 'slide', // none/fade/slide/convex/concave/zoom
+ 
+             // More info https://github.com/hakimel/reveal.js#dependencies
+             dependencies: [
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true },
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/math/math.js', async: true }
+             ]
+         });
+ &lt;/script&gt;
+ &lt;/body&gt;
</t>
<t tx="leo.20170114173925.60">(uncached) leo.20161104010457.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.61">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.62">@others
</t>
<t tx="leo.20170114173925.63">(uncached) leo.20161104010457.2
Diff...
+ ## 2016-09-30 第三週
+ 
</t>
<t tx="leo.20170114173925.64">## 2016-09-30 第三週

</t>
<t tx="leo.20170114173925.65"></t>
<t tx="leo.20170114173925.66">(uncached) leo.20161014111031.38
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.67">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.68">@others
</t>
<t tx="leo.20170114173925.69">(uncached) leo.20161014111031.39
Diff...
+ ## 複製網誌和簡報的設定檔
+ ## 到2016fallcadp_hw的倉儲
+ 
+ &lt;iframe src="https://player.vimeo.com/video/190065696" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
+ 
+ 
</t>
<t tx="leo.20170114173925.7">&lt;body&gt;
@others
&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;
&lt;script&gt;
        // More info https://github.com/hakimel/reveal.js#configuration
        Reveal.initialize({
            controls: true,
            progress: true,
            history: true,
            center: true,

            transition: 'slide', // none/fade/slide/convex/concave/zoom

            // More info https://github.com/hakimel/reveal.js#dependencies
            dependencies: [
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/math/math.js', async: true }
            ]
        });
&lt;/script&gt;
&lt;/body&gt;
</t>
<t tx="leo.20170114173925.70">## 複製網誌和簡報的設定檔
## 到2016fallcadp_hw的倉儲

&lt;iframe src="https://player.vimeo.com/video/190065696" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;


</t>
<t tx="leo.20170114173925.71"></t>
<t tx="leo.20170114173925.72">(uncached) leo.20161104010537.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.73">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.74">@others
</t>
<t tx="leo.20170114173925.75">(uncached) leo.20161104010537.2
Diff...
+ ## 更改2016fallcadp_hw的
+ ## README.md檔案
+ 
+ &lt;iframe src="https://player.vimeo.com/video/190066620" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
+ 
+ 
</t>
<t tx="leo.20170114173925.76">## 更改2016fallcadp_hw的
## README.md檔案

&lt;iframe src="https://player.vimeo.com/video/190066620" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;


</t>
<t tx="leo.20170114173925.77"></t>
<t tx="leo.20170114173925.78">(uncached) leo.20161014111031.40
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170114173925.79">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170114173925.8">		&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
@others
</t>
<t tx="leo.20170114173925.80">@others
</t>
<t tx="leo.20170114173925.81">(uncached) leo.20161104010854.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.82">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170114173925.83">@others
</t>
<t tx="leo.20170114173925.84">(uncached) leo.20161104010854.2
Diff...
+ ## 2016-10-07 第四週
+ 
</t>
<t tx="leo.20170114173925.85">## 2016-10-07 第四週

</t>
<t tx="leo.20170114173925.86"></t>
<t tx="leo.20170114173925.87">(uncached) leo.20161014111031.41
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
+ &lt;!-- 請注意, @others 不可以內縮 --&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.88">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
&lt;!-- 請注意, @others 不可以內縮 --&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;



						
</t>
<t tx="leo.20170114173925.89">@others
</t>
<t tx="leo.20170114173925.9">(uncached) leo.20161014111031.5
Diff...
- 		&lt;meta name="author" content="Hakim El Hattab"&gt;
+ &lt;div class="reveal"&gt;
  @others
+ &lt;/div&gt;
+ 
</t>
<t tx="leo.20170114173925.90">(uncached) leo.20161014111031.42
Diff...
+ ## 設定使用者資料
+ ## 讓可攜程式更方便
+ 
+ &lt;iframe src="https://player.vimeo.com/video/190072906" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170114173925.91">## 設定使用者資料
## 讓可攜程式更方便

&lt;iframe src="https://player.vimeo.com/video/190072906" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170114173925.92"></t>
<t tx="leo.20170114173925.93">(uncached) leo.20161014111031.43
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
+ &lt;!-- 請注意, @others 不可以內縮 --&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 
+ 						
</t>
<t tx="leo.20170114173925.94">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
&lt;!-- 請注意, @others 不可以內縮 --&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;



						
</t>
<t tx="leo.20170114173925.95">@others
</t>
<t tx="leo.20170114173925.96">(uncached) leo.20161014111031.44
Diff...
+ ## 用2016fallcadp_bg6的名稱
+ ## 建立小組倉儲
+ 
+ &lt;iframe src="https://player.vimeo.com/video/190075715" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170114173925.97">## 用2016fallcadp_bg6的名稱
## 建立小組倉儲

&lt;iframe src="https://player.vimeo.com/video/190075715" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170114173925.98"></t>
<t tx="leo.20170114173925.99">(uncached) leo.20161103232830.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
</tnodes>
</leo_file>
